In [11]:
def square_1(x):
    return(x**2)

square_2 = lambda x: x**2

print(square_1(2))
print(square_2(2))

squared = [square(x) for x in range(10)]
print(squared)

4
4
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [5]:
multiply = lambda x, y: x * y
print(multiply(5, 2))

10


In [12]:
def generate_range():
    return lambda upper: range(upper)
custom_range = generate_range()

for i in custom_range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [23]:
import re

school_dash = ['Calculus', 'Philosophy', 'Art-History', 'Computer-Science']

school_space = [(lambda x: x.replace('-', ' '))(x) for x in school_dash]
print(school_space)

school_space = [(lambda y: re.sub('-', ' ', y))(y) for y in school_dash]
print(school_space)

school_sort = sorted(school_space, key = lambda x: x[-1])
print(school_sort)

['Calculus', 'Philosophy', 'Art History', 'Computer Science']
['Calculus', 'Philosophy', 'Art History', 'Computer Science']
['Computer Science', 'Calculus', 'Philosophy', 'Art History']


In [25]:
div = lambda num, denom: num / denom if denom != 0 else 0

print(div(5, 10))
print(div(5, 0))

0.5
0


In [29]:
import datetime
class Person:
   def __init__(self, first_name, last_name, dob, address, telephone, email):
       self.first_name = first_name
       self.last_name = last_name
       self.dob = dob
       self.address = address
       self.telephone = telephone
       self.email = email
   def age(self):
       today = datetime.date.today()
       age = today.year - self.dob.year
       if today < datetime.date(today.year, self.dob.month, self.dob.day):
           age -= 1
       return age

person = Person(
   "himanshu",
   "aggarwal",
   datetime.date(1992, 3, 26),
   "ABC, MIAMI",
   "480 395 8900",
   "himanshu.aggarwal@ironhack.com"
)

print(person.first_name)
print(person.last_name)
print(person.email)
print(person.age())
print(person)

himanshu
aggarwal
himanshu.aggarwal@ironhack.com
27


In [43]:
import numpy as np

def ordinary_least_squares(X, y):
    # This function returns the regression coefficients of a linear model
    # input: X - predictor variables and y - response variables
    # output: regression coefficients
    
    xtx = np.dot(X.T, X) ## x-transpose times x
    xtx_inv = np.linalg.inv(xtx) ## inverse of x-transpose times x
    xty = np.dot(X.T, y) ## x-transpose times y
    return np.dot(xtx_inv, xty)

X = np.array([[1, 4, 5], [2, -1, 3], [1, 4, 5], [2, -1, 3], [1, 4, 5], [2, -1, 3]])
y = np.array([5, 3])


coefficients = ordinary_least_squares(X, y)
predicted = np.dot(X, coefficients)

print(list(coefficients))
print(list(predicted))

class LinearReg:
    def __init__(self, fit_intercept=True):
        self.fit_intercept = fit_intercept
        self.coefficients = None
        self.intercept = None
        
    def fit(self, X, y):
        # This function returns the fitted linear model 
        # input: X - predictor variables and y - response variables
        # output: regression coefficients
        
        xtx = np.dot(X.T, X) ## x-transpose times x
        xtx_inv = np.linalg.inv(xtx) ## inverse of x-transpose times x
        xty = np.dot(X.T, y) ## x-transpose times y
        coefficients = np.dot(xtx_inv, xty)
        
        if self.fit_intercept:
            self.intercept = coefficients[0]
            self.coefficients = coefficients[1:]
        else:
            self.intercept = 0
            self.coefficients = coefficients
            
            
    def predict(self, X):
        # This function returns the predicted values
        # input: array of dependent variables
        # output: predicted values
        if len(X.shape) == 1:
            X = X.reshape(-1,1) 
            return self.intercept_ + np.dot(X, self.coef_) 

linreg = LinearReg()
linreg.fit(X, y)

[16.0, 16.0, -8.0]
[40.0, -8.0]


In [68]:
import random
import numpy as np

X = []
x = []
y = []

x_size = random.randint(2, 10)
y_size = n_size
n_size = random.randint(5, 10)

print(f'There are {n_size} observations and {x_size} predictors in this data set.\n')

for i in range(n_size):
    for j in range(x_size):
        x.append(random.randint(-10, 10))
    X.append(x)
    y.append(random.randint(-10, 10))
    x = []

X = np.array(X)
y = np.array(y)
print(f'{X} is the predictor matrix.\n')
print(f'{y} is the outcome vector.\n')

def ordinary_least_squares(X, y):
    xtx = np.dot(X.T, X) ## x-transpose times x
    xtx_inv = np.linalg.inv(xtx) ## inverse of x-transpose times x
    xty = np.dot(X.T, y) ## x-transpose times y
    return np.dot(xtx_inv, xty)

coefficients = ordinary_least_squares(X, y)
predicted = np.dot(X, coefficients)


print(list(coefficients), '\n')
print(list(predicted))

There are 8 observations and 6 predictors in this data set.

[[  7   4   2   8  -8   3]
 [  8   5   1   5   0   4]
 [ 10  -6  -9  -7   3  -1]
 [-10  -9  -2  -6  10   9]
 [  3   6   4  -9  -7   6]
 [  8  -7   6  -4  -8  -5]
 [ -5  -7   4  -2   6   1]
 [ -6  -1   1  -5   7   2]] is the predictor matrix.

[-10   8  -5   6  -9   2   9  -4] is the outcome vector.

[0.3734097704982147, -0.30773707598818173, 0.9860681680566409, 0.43285686654883154, 1.1168578061304713, -0.19815791501219732] 

[-2.711424836041653, 3.8063136247968186, -2.7753600840367394, 3.851415269700154, -9.68458440413385, 1.382346364064725, 9.868658540325729, 4.310751101200281]


In [ ]:
X = np.array([[4, 4, 5], [2, -1, 3], [8, 6, 5], [2, -1, 3], [1, 4, 5], [2, -1, 3]])
y = np.array([5, 3])