In [2]:
import numpy as np

In [12]:
a = np.random.random((10,4))
print(a, '\n')
print(a[0], '\n')
print(a[:,0], '\n')
print(a[0, 0], '\n')
print(a.shape, '\n')
print(a.size, '\n')

[[0.74043853 0.19280517 0.55782742 0.08838919]
 [0.31702851 0.21572281 0.07296651 0.45308184]
 [0.18154719 0.60312952 0.78769164 0.89484086]
 [0.48298567 0.86900949 0.30465194 0.50205391]
 [0.94813348 0.68835476 0.09456254 0.86312801]
 [0.58449241 0.4017973  0.84284572 0.07667925]
 [0.01832748 0.81843315 0.57139104 0.20436776]
 [0.3614187  0.03988044 0.00378841 0.1161749 ]
 [0.83996364 0.636979   0.33006698 0.50906694]
 [0.04758389 0.00480991 0.51717279 0.09313111]] 

[0.74043853 0.19280517 0.55782742 0.08838919] 

[0.74043853 0.31702851 0.18154719 0.48298567 0.94813348 0.58449241
 0.01832748 0.3614187  0.83996364 0.04758389] 

0.7404385257708863 

(10, 4) 

40 



In [13]:
b = np.random.random((5,2,3))
print(b, '\n')

[[[0.80314298 0.94348922 0.73130399]
  [0.58775671 0.8840754  0.66786192]]

 [[0.94967119 0.53138031 0.62728357]
  [0.27382761 0.47964481 0.79211811]]

 [[0.91734506 0.6070144  0.27919372]
  [0.42010434 0.9463896  0.26366459]]

 [[0.94098453 0.95687984 0.15051591]
  [0.59357546 0.88166385 0.27090677]]

 [[0.02739486 0.1076433  0.38399801]
  [0.15538041 0.03156919 0.37258295]]] 



In [14]:
c = np.random.random((2,3,4,5))
print(c, '\n\n')
print(c[0], '\n\n')
print(c[0,1,2,3], '\n\n')

[[[[0.30911232 0.12210563 0.23814467 0.89087877 0.72775345]
   [0.2124176  0.91305418 0.55818412 0.58146472 0.73071351]
   [0.92778778 0.58834094 0.98007857 0.8750924  0.33847826]
   [0.92490009 0.12083391 0.70424948 0.09327755 0.36690605]]

  [[0.06089794 0.81833591 0.28722261 0.7898227  0.48027526]
   [0.92277705 0.92719115 0.94847209 0.10783835 0.61126798]
   [0.00673583 0.87585539 0.35706666 0.48116604 0.35539708]
   [0.07427383 0.33036728 0.94584192 0.48894024 0.40960802]]

  [[0.40406789 0.92375562 0.83706941 0.50486805 0.36316463]
   [0.37557538 0.65915065 0.70659989 0.40296809 0.81198438]
   [0.77478372 0.69805958 0.39794712 0.72134299 0.74007882]
   [0.73926601 0.37575831 0.17284878 0.145418   0.28646687]]]


 [[[0.42226245 0.25985042 0.29563501 0.121921   0.63054797]
   [0.78053762 0.99092111 0.65427538 0.02591361 0.26629875]
   [0.81124951 0.58072218 0.7863859  0.04405452 0.47959524]
   [0.2762929  0.23982511 0.58121469 0.28944006 0.56415052]]

  [[0.88688873 0.54948775 0.19

In [19]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
d = np.array(lst_lst)
print(d, '\n')

print(np.sum(d), '\n')
print(np.sum(d, axis=0), '\n')
print(np.sum(d, axis=1), '\n')
print(np.sum(d[:1]), '\n')
print(np.sum(d[1:]), '\n')
print(np.sum(d[1:2]), '\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

78 

[22 26 30] 

[ 6 15 24 33] 

6 

72 

15 

